# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - legaltech-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: azure-webapp-legaltech-app-production
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !.git
            !.github
            !node_modules
            !.next/cache
            !**/*.log
            !docs
            !prompts
            !sql

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: release
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1012C839CADA4AF4B9A66689E9FEAA9A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_62B127FEA4924676A5A826A9323603FD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BAD3939A62CF4434944C6FCDBF04741B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'legaltech-app'
          slot-name: 'Production'
          package: release
          